### ISSUE TITLE
Difference between Readme and code

### ISSUE THREAD

**Issue by andre-m-dev** [viafintech/sps_king#4]
The Readme says: "OPTIONAL: Currency, CHF by default", but the linked code says: "self.currency ||= 'EUR'" see: 
https://github.com/viafintech/sps_king/blob/60872692e92e5746ff07d361fcb2195e82ee2140/lib/sps_king/transaction.rb#L46

**Comment by tobischo** [comment]
You are right. The documentation is correct here and it is not correct in the code. I will adjust it and release it as a bug fix release.

It just doesn't make any sense to default to EUR here.

In our code we never noticed because we always pass it explicitly

**Comment by tobischo** [comment]
Resolved and released in v0.3.1
